apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sql.secret }}
type: Opaque
data:
  mysql_root_password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sql.service }}
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306







