apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: {{ .Values.sql.name }}
  labels:
    app: {{ .Values.sql.name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.sql.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.sql.name }}
    spec:
      containers:
        - name: {{ .Values.sql.name }}
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name:  {{ .Values.sql.secret }}
                  key: mysql_root_password

